### ISSUE TITLE
Skapa händelser som inloggad

### ISSUE THREAD

**Issue by HenrikGabrielsson** [mf222nb/1DV450_Laboration_3#4]
Om man loggar ut och går till **/app/#/create** så kan man fortfarande skapa händelser, som den senaste inloggade användaren. Därför ska du nog ta bort sessionskakor helt när du loggar ut istället för att bara sätta "IsLoggedIn" till false. 
Utan cookies går det dock inte att skapa något så det är bra.

**Comment by mf222nb** [comment]
Har tagit bort det som ligger i sessionstorage när man loggar ut så nu går det inte att skapa händelser som inloggad.
